export const TYPE_USER_RESIDENT = 'TYPE_USER_RESIDENT';
export const TYPE_USER_VISITOR = 'TYPE_USER_VISITOR';
export const ERROR_TYPE_FILEDS_FILLING = 'ERROR_TYPE_FILEDS_FILLING';
export const ERROR_TYPE_CONDITIONS_AGREEMENT = 'ERROR_TYPE_CONDITIONS_AGREEMENT';
export const ERROR_TYPE_SERVER = 'ERROR_TYPE_SERVER';

const _BASE_PATH = '';

export const BASE_PATH = _BASE_PATH;

